[tool.poetry]
name = "tsm-stack"
version = "0.1.0"
description = ""
authors = ["Ben <ben@ahnlab.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
boto3 = "^1.35.38"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
